apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: devops-demo
data:
  init.sql: |
    CREATE DATABASE users_db;
    \c users_db;
    CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL
    );